### ISSUE TITLE
ssptool validate and kwalify disagree

### ISSUE THREAD

**Issue by git-ingham** [jenglish/ssptool#11]
I am trying to make sure everything is consistent.  However, it appears that the validation options are not consistent with each other.  
```
$ schema=${SD}/component/v3.1.0.yaml
$ pykwalify -d Desktops/AccessControl/component.yaml  -s $schema
 INFO - validation.valid
$ node main.js validate
AccessControl/component.yaml
        .satisfies[0]: should NOT have additional properties
        .satisfies[0]: should NOT have additional properties
```
Which is correct?

Thanks

**Comment by git-ingham** [comment]
This might be useful info I forgot to add:
```
$ node main.js -V
0.4.4
```

**Comment by jenglish** [comment]
Hard to say -- `ssptool validate` should also report the name of the additional property that it doesn't like,

This is implemented in git on the master branch, but I neglected to tag a new release (sorry) -- can you update to the latest version and try again?

**Comment by git-ingham** [comment]
Latest version (from earlier today) seems to work OK. Thanks.
