### ISSUE TITLE
Empty ssptool.yaml file causes error

### ISSUE THREAD

**Issue by git-ingham** [jenglish/ssptool#12]
If I create an empty ssptool.yaml, I get the following error:

    $ > ssptool.yaml
    $ node main.js server
    Loading data...
    Cannot set property '_errors' of undefined
    $ rm ssptool.yaml
    $ node main.js server
    Loading data...
    Initializing...
    Listening on http://localhost:3000
    Ready.

If an ssptool.yaml must have contents, it would be nice to get a better error message.

(side note: it would be nice to know what can go into that file)

**Comment by jenglish** [comment]
Should be fixed now.

>  (side note: it would be nice to know what can go into that file)

Mainly it's the command-line options (datadir: and docdir:), plus document definitions. Updated the wiki to try to make this more apparent.

The authoritative definition of config file contents is the json-schema in `lib/config.js`; `ssptool validate` also checks the configuration file.
