### ISSUE TITLE
Non-localhost option for web server

### ISSUE THREAD

**Issue by git-ingham** [jenglish/ssptool#14]
We need ssptool to run on a non-127.0.0.1 IP address.  I have kludged it into what we are running (hard-coded 0.0.0.0), but it would be nice to have an "official" option for specifying the address(es) on which to listen for connections.  (Same for port, but we can live with 3000)

**Comment by jenglish** [comment]
You may specify a different port on the command-line with:
```
ssptool server -p 8080
```
At present this can only be specified on the command line, not in the config file.  (Do you need that? It's doable, just takes some replumbing).

**Comment by jenglish** [comment]
Re: listening IP address: `ssptool server` actually does listen on all addresses (0.0.0.0).

The startup message says "Listening on http://localhost:%d" mainly to present a URL that can be copied and pasted into a web browser; more accurately it should just say "listening on port %d"

**Comment by git-ingham** [comment]
Specifying the port in the config file would be nice, but not necessary.  Any way we run it could include the command-line option.
