### ISSUE TITLE
Integration with PatternFly

### ISSUE THREAD

**Issue by shawndwells** [jenglish/ssptool#6]
My hobby project over the break is taking ssptool and integrating it with PatternFly. Is this something you'd be interested in merging upstream?

PatternFly is a standardized UI/UX framework. Sets nice style sheets, graphs, etc.

![image](https://user-images.githubusercontent.com/5713754/34324653-9a0dcb7c-e848-11e7-8641-5cb5983a411e.png)

![image](https://user-images.githubusercontent.com/5713754/34324655-a5ed8ec8-e848-11e7-9c57-f186688e1f2f.png)

![image](https://user-images.githubusercontent.com/5713754/34324761-9e8859f8-e84b-11e7-914e-193140011a33.png)

**Comment by shawndwells** [comment]
additional references...
http://www.patternfly.org/

http://www.patternfly.org/pattern-library/

**Comment by jenglish** [comment]
Yes, that is something I'd be interested in!

I started with Bootstrap mainly on the grounds that it would be more familiar to other developers,  though I had not used it before myself. I haven't been entirely happy with it TBH. PatternFly looks like a better choice. (I've also looked at Bulma and Semantic).

**Comment by shawndwells** [comment]
PatternFly has a bunch of frameworks, like this one for React:
https://github.com/patternfly/patternfly-react

My interest is to create a better UI, because IMHO this should eventually ship as part of Fedora/RHEL. Working on that here:
http://ssptool.securitycentral.io/

I'm not familiar with Express... looking at how to convert things to something with NodeJS+React+AngularJS so I can pull in better visuals.

**Comment by jenglish** [comment]
Revisited this issue and it turned out to be much easier than I expected. Since PatternFly 3 is based on Bootstrap 3, the base patternfly stylesheet worked as a drop-in replacement for `bootstrap.min.css` with no other changes required.

The typography is *much* nicer IMO, even before adopting PF-specific design elements.

**Comment by shawndwells** [comment]
@jenglish nice! I'm no longer working in this space (or at Red Hat!) but @trevorbryant is, and may find this extremely interesting.
